package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/nais/teams-backend/pkg/db"
	"github.com/nais/teams-backend/pkg/graph/generated"
	"github.com/nais/teams-backend/pkg/types"
)

// Action is the resolver for the action field.
func (r *auditLogResolver) Action(ctx context.Context, obj *db.AuditLog) (types.AuditAction, error) {
	return types.AuditAction(obj.Action), nil
}

// ComponentName is the resolver for the componentName field.
func (r *auditLogResolver) ComponentName(ctx context.Context, obj *db.AuditLog) (types.ComponentName, error) {
	return types.ComponentName(obj.ComponentName), nil
}

// TargetType is the resolver for the targetType field.
func (r *auditLogResolver) TargetType(ctx context.Context, obj *db.AuditLog) (types.AuditLogsTargetType, error) {
	return types.AuditLogsTargetType(obj.TargetType), nil
}

// AuditLog returns generated.AuditLogResolver implementation.
func (r *Resolver) AuditLog() generated.AuditLogResolver { return &auditLogResolver{r} }

type auditLogResolver struct{ *Resolver }
