package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/nais/teams-backend/pkg/db"
	"github.com/nais/teams-backend/pkg/graph/generated"
	"github.com/nais/teams-backend/pkg/types"
)

// Action is the resolver for the action field.
func (r *auditLogResolver) Action(ctx context.Context, obj *db.AuditLog) (types.AuditAction, error) {
	return types.AuditAction(obj.Action), nil
}

// ComponentName is the resolver for the componentName field.
func (r *auditLogResolver) ComponentName(ctx context.Context, obj *db.AuditLog) (types.ComponentName, error) {
	return types.ComponentName(obj.ComponentName), nil
}

// TargetType is the resolver for the targetType field.
func (r *auditLogResolver) TargetType(ctx context.Context, obj *db.AuditLog) (types.AuditLogsTargetType, error) {
	return types.AuditLogsTargetType(obj.TargetType), nil
}

// AuditLog returns generated.AuditLogResolver implementation.
func (r *Resolver) AuditLog() generated.AuditLogResolver { return &auditLogResolver{r} }

type auditLogResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *auditLogResolver) ID(ctx context.Context, obj *db.AuditLog) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

func (r *auditLogResolver) CorrelationID(ctx context.Context, obj *db.AuditLog) (string, error) {
	panic(fmt.Errorf("not implemented: CorrelationID - correlationID"))
}
