package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/nais/teams-backend/pkg/authz"
	"github.com/nais/teams-backend/pkg/db"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (db.AuthenticatedUser, error) {
	return authz.ActorFromContext(ctx).User, nil
}
