apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teams-backend.fullname" . }}
  labels:
    {{- include "teams-backend.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /oauth2
            backend:
              service:
                name: {{ include "teams-backend.fullname" . }}
                port:
                  name: http
            pathType: ImplementationSpecific
          - path: /query
            backend:
              service:
                name: {{ include "teams-backend.fullname" . }}
                port:
                  name: http
            pathType: ImplementationSpecific
