apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "teams-backend.fullname" . }}
  labels:
    {{- include "teams-backend.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nais-system
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: hookd
          app.kubernetes.io/name: hookd
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
  - Egress
