apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teams-backend.fullname" . }}
  labels:
    {{- include "teams-backend.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 1m
    port: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "teams-backend.selectorLabels" . | nindent 6 }}
