with-expecter: true
disable-version-string: true
inpackage: true
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
packages:
  github.com/nais/teams-backend/pkg/auditlogger:
    interfaces:
      AuditLogger:
  github.com/nais/teams-backend/pkg/authn:
    interfaces:
      Handler:
  github.com/nais/teams-backend/pkg/azureclient:
    interfaces:
      Client:
  github.com/nais/teams-backend/pkg/db:
    interfaces:
      AuthenticatedUser:
      Database:
  github.com/nais/teams-backend/pkg/deployproxy:
    interfaces:
      Proxy:
  github.com/nais/teams-backend/pkg/logger:
    interfaces:
      Logger:
  github.com/nais/teams-backend/pkg/reconcilers:
    interfaces:
      Reconciler:
  github.com/nais/teams-backend/pkg/reconcilers/dependencytrack:
    interfaces:
      Client:
  github.com/nais/teams-backend/pkg/reconcilers/github/team:
    interfaces:
      TeamsService:
      GraphClient:
  github.com/nais/teams-backend/pkg/teamsync:
    interfaces:
      Queue:
      Handler:
