BEGIN;

ALTER SEQUENCE reconcile_errors_id_seq RENAME TO reconciler_errors_id_seq;

ALTER TABLE service_account_roles RENAME CONSTRAINT team_or_service_account TO service_account_roles_check;
ALTER TABLE user_roles RENAME CONSTRAINT team_or_service_account TO user_roles_check;
ALTER TABLE slack_alerts_channels RENAME CONSTRAINT slack_alerts_channels_channel_name TO slack_alerts_channels_channel_name_check;
ALTER TABLE teams RENAME CONSTRAINT teams_purpose_not_empty_check TO teams_purpose_check;
ALTER TABLE teams RENAME CONSTRAINT teams_slack_alerts_channel TO teams_slack_channel_check;
ALTER TABLE reconciler_errors RENAME CONSTRAINT reconciler_errors_team_id_reconciler_key TO reconciler_errors_team_slug_reconciler_key;

ALTER INDEX users_external_id_idx RENAME TO users_external_id_key;
ALTER INDEX audit_logs_created_at_desc_idx RENAME TO audit_logs_created_at_idx;
ALTER INDEX idx_reconciler_errors_created_at_desc RENAME TO reconciler_errors_created_at_idx;
ALTER INDEX unique_global_service_account_role_idx RENAME TO service_account_roles_service_account_id_role_name_idx;
ALTER INDEX unique_global_user_role_idx RENAME TO user_roles_user_id_role_name_idx;
ALTER INDEX unique_service_account_service_account_role_idx RENAME TO service_account_roles_service_account_id_role_name_target_s_idx;
ALTER INDEX unique_service_account_user_role_idx RENAME TO user_roles_user_id_role_name_target_service_account_id_idx;
ALTER INDEX unique_team_service_account_role_idx RENAME TO service_account_roles_service_account_id_role_name_target_t_idx;
ALTER INDEX unique_team_user_role_idx RENAME TO user_roles_user_id_role_name_target_team_slug_idx;

COMMIT;