BEGIN;

ALTER TABLE audit_logs ALTER COLUMN action TYPE TEXT;

DROP TYPE audit_action;

CREATE TYPE audit_action AS ENUM (
    'azure:group:add-member',
    'azure:group:add-members',
    'azure:group:create',
    'azure:group:delete',
    'azure:group:delete-member',
    'dependencytrack:group:create',
    'github:team:add-member',
    'github:team:add-members',
    'github:team:create',
    'github:team:delete',
    'github:team:delete-member',
    'github:team:map-sso-user',
    'google:gar:delete',
    'google:gcp:delete-project',
    'google:gcp:project:assign-permissions',
    'google:gcp:project:create-cnrm-service-account',
    'google:gcp:project:create-project',
    'google:gcp:project:delete-cnrm-service-account',
    'google:gcp:project:enable-google-apis',
    'google:gcp:project:set-billing-info',
    'google:workspace-admin:add-member',
    'google:workspace-admin:add-members',
    'google:workspace-admin:add-to-gke-security-group',
    'google:workspace-admin:create',
    'google:workspace-admin:delete',
    'google:workspace-admin:delete-member',
    'graphql-api:api-key:create',
    'graphql-api:api-key:delete',
    'graphql-api:reconcilers:configure',
    'graphql-api:reconcilers:disable',
    'graphql-api:reconcilers:enable',
    'graphql-api:reconcilers:reset',
    'graphql-api:reconcilers:update-team-state',
    'graphql-api:roles:assign-global-role',
    'graphql-api:roles:revoke-global-role',
    'graphql-api:service-account:create',
    'graphql-api:service-account:delete',
    'graphql-api:service-account:update',
    'graphql-api:team:add-member',
    'graphql-api:team:add-owner',
    'graphql-api:team:create',
    'graphql-api:team:disable',
    'graphql-api:team:enable',
    'graphql-api:team:remove-member',
    'graphql-api:team:set-member-role',
    'graphql-api:team:sync',
    'graphql-api:team:update',
    'graphql-api:teams:delete',
    'graphql-api:teams:request-delete',
    'graphql-api:users:sync',
    'legacy-importer:team:add-member',
    'legacy-importer:team:add-owner',
    'legacy-importer:team:create',
    'legacy-importer:user:create',
    'nais:deploy:provision-deploy-key',
    'nais:namespace:create-namespace',
    'nais:namespace:delete-namespace',
    'usersync:assign-admin-role',
    'usersync:create',
    'usersync:delete',
    'usersync:list:local',
    'usersync:list:remote',
    'usersync:prepare',
    'usersync:revoke-admin-role',
    'usersync:update'
);

ALTER TABLE audit_logs ALTER COLUMN action TYPE audit_action USING action::audit_action;

COMMIT;