// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: apikey.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (api_key, user_id) VALUES ($1, $2)
`

type CreateAPIKeyParams struct {
	ApiKey string
	UserID uuid.UUID
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey, arg.ApiKey, arg.UserID)
	return err
}
