// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/nais/console/pkg/slug"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (correlation_id, actor, system_name, target_user, target_team_slug, action, message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditLogParams struct {
	CorrelationID  uuid.UUID
	Actor          sql.NullString
	SystemName     SystemName
	TargetUser     sql.NullString
	TargetTeamSlug *slug.Slug
	Action         AuditAction
	Message        string
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.CorrelationID,
		arg.Actor,
		arg.SystemName,
		arg.TargetUser,
		arg.TargetTeamSlug,
		arg.Action,
		arg.Message,
	)
	return err
}

const getAuditLogsForTeam = `-- name: GetAuditLogsForTeam :many
SELECT id, created_at, correlation_id, system_name, actor, target_user, target_team_slug, action, message FROM audit_logs
WHERE target_team_slug = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetAuditLogsForTeam(ctx context.Context, targetTeamSlug *slug.Slug) ([]*AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsForTeam, targetTeamSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CorrelationID,
			&i.SystemName,
			&i.Actor,
			&i.TargetUser,
			&i.TargetTeamSlug,
			&i.Action,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
