// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: reconciler_errors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/console/pkg/slug"
)

const clearReconcilerErrorsForTeam = `-- name: ClearReconcilerErrorsForTeam :exec
DELETE FROM reconciler_errors
WHERE team_slug = $1 AND reconciler = $2
`

type ClearReconcilerErrorsForTeamParams struct {
	TeamSlug   slug.Slug
	Reconciler ReconcilerName
}

func (q *Queries) ClearReconcilerErrorsForTeam(ctx context.Context, arg ClearReconcilerErrorsForTeamParams) error {
	_, err := q.db.Exec(ctx, clearReconcilerErrorsForTeam, arg.TeamSlug, arg.Reconciler)
	return err
}

const getTeamReconcilerErrors = `-- name: GetTeamReconcilerErrors :many
SELECT id, correlation_id, reconciler, created_at, error_message, team_slug FROM reconciler_errors
WHERE team_slug = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTeamReconcilerErrors(ctx context.Context, teamSlug slug.Slug) ([]*ReconcilerError, error) {
	rows, err := q.db.Query(ctx, getTeamReconcilerErrors, teamSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReconcilerError
	for rows.Next() {
		var i ReconcilerError
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.Reconciler,
			&i.CreatedAt,
			&i.ErrorMessage,
			&i.TeamSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReconcilerErrorForTeam = `-- name: SetReconcilerErrorForTeam :exec
INSERT INTO reconciler_errors (correlation_id, team_slug, reconciler, error_message)
VALUES ($1, $2, $3, $4)
ON CONFLICT(team_slug, reconciler) DO
    UPDATE SET correlation_id = $1, created_at = NOW(), error_message = $4
`

type SetReconcilerErrorForTeamParams struct {
	CorrelationID uuid.UUID
	TeamSlug      slug.Slug
	Reconciler    ReconcilerName
	ErrorMessage  string
}

func (q *Queries) SetReconcilerErrorForTeam(ctx context.Context, arg SetReconcilerErrorForTeamParams) error {
	_, err := q.db.Exec(ctx, setReconcilerErrorForTeam,
		arg.CorrelationID,
		arg.TeamSlug,
		arg.Reconciler,
		arg.ErrorMessage,
	)
	return err
}
