// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: repository_authorizations.sql

package sqlc

import (
	"context"
)

const addRepositoryAuthorization = `-- name: AddRepositoryAuthorization :one
INSERT INTO repository_authorizations (team_slug, github_repository, repository_authorization)
VALUES ($1, $2, $3)
RETURNING team_slug, github_repository, repository_authorization
`

type AddRepositoryAuthorizationParams struct {
	TeamSlug                string
	GithubRepository        string
	RepositoryAuthorization RepositoryAuthorizationEnum
}

func (q *Queries) AddRepositoryAuthorization(ctx context.Context, arg AddRepositoryAuthorizationParams) (*RepositoryAuthorization, error) {
	row := q.db.QueryRow(ctx, addRepositoryAuthorization, arg.TeamSlug, arg.GithubRepository, arg.RepositoryAuthorization)
	var i RepositoryAuthorization
	err := row.Scan(&i.TeamSlug, &i.GithubRepository, &i.RepositoryAuthorization)
	return &i, err
}
