// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: team_metadata.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTeamMetadata = `-- name: GetTeamMetadata :one
SELECT id, created_at, created_by_id, updated_by_id, updated_at, team_id, key, value FROM team_metadata WHERE team_id = $1 LIMIT 1
`

func (q *Queries) GetTeamMetadata(ctx context.Context, teamID uuid.UUID) (*TeamMetadatum, error) {
	row := q.db.QueryRow(ctx, getTeamMetadata, teamID)
	var i TeamMetadatum
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.UpdatedAt,
		&i.TeamID,
		&i.Key,
		&i.Value,
	)
	return &i, err
}
