// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: team_metadata.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTeamMetadata = `-- name: GetTeamMetadata :many
SELECT team_id, key, value FROM team_metadata WHERE team_id = $1
`

func (q *Queries) GetTeamMetadata(ctx context.Context, teamID uuid.UUID) ([]*TeamMetadatum, error) {
	rows, err := q.db.Query(ctx, getTeamMetadata, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TeamMetadatum
	for rows.Next() {
		var i TeamMetadatum
		if err := rows.Scan(&i.TeamID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
