// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user_roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO user_roles (id, user_id, role_id, created_by_id) VALUES ($1, $2, $3, $4)
`

type AddRoleToUserParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	RoleID      uuid.UUID
	CreatedByID uuid.NullUUID
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.Exec(ctx, addRoleToUser,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.CreatedByID,
	)
	return err
}
