// Code generated by mockery v2.14.0. DO NOT EDIT.

package teamsync

import (
	context "context"

	db "github.com/nais/console/pkg/db"
	mock "github.com/stretchr/testify/mock"

	reconcilers "github.com/nais/console/pkg/reconcilers"

	sqlc "github.com/nais/console/pkg/sqlc"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// InitReconcilers provides a mock function with given fields: ctx
func (_m *MockHandler) InitReconcilers(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReconcileTeam provides a mock function with given fields: ctx, input
func (_m *MockHandler) ReconcileTeam(ctx context.Context, input reconcilers.Input) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcilers.Input) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveReconciler provides a mock function with given fields: reconcilerName
func (_m *MockHandler) RemoveReconciler(reconcilerName sqlc.ReconcilerName) {
	_m.Called(reconcilerName)
}

// Schedule provides a mock function with given fields: input
func (_m *MockHandler) Schedule(input reconcilers.Input) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(reconcilers.Input) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReconcilerFactories provides a mock function with given fields: factories
func (_m *MockHandler) SetReconcilerFactories(factories ReconcilerFactories) {
	_m.Called(factories)
}

// UseReconciler provides a mock function with given fields: reconciler
func (_m *MockHandler) UseReconciler(reconciler db.Reconciler) error {
	ret := _m.Called(reconciler)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.Reconciler) error); ok {
		r0 = rf(reconciler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandler(t mockConstructorTestingTNewMockHandler) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
