package console

import (
	"fmt"
	"time"
)

func Strp(s string) *string {
	return &s
}

func StringWithFallback(strp *string, fallback string) string {
	if strp == nil || *strp == "" {
		return fallback
	}
	return *strp
}

// TeamPurpose Get a default team purpose
func TeamPurpose(purpose *string) string {
	return StringWithFallback(
		purpose,
		fmt.Sprintf("auto-generated by nais console on %s", time.Now().Format(time.RFC1123Z)),
	)
}

// Truncate will truncate the string s to the given length
func Truncate(s string, length int) string {
	if len(s) <= length {
		return s
	}
	return s[:length]
}
