// Code generated by mockery v2.14.0. DO NOT EDIT.

package github_team_reconciler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGraphClient is an autogenerated mock type for the GraphClient type
type MockGraphClient struct {
	mock.Mock
}

// Query provides a mock function with given fields: ctx, q, variables
func (_m *MockGraphClient) Query(ctx context.Context, q interface{}, variables map[string]interface{}) error {
	ret := _m.Called(ctx, q, variables)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}) error); ok {
		r0 = rf(ctx, q, variables)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockGraphClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGraphClient creates a new instance of MockGraphClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGraphClient(t mockConstructorTestingTNewMockGraphClient) *MockGraphClient {
	mock := &MockGraphClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
