name: Build and deploy image
on:
  push:
    paths-ignore:
      - "charts/**"
      - "*.md"
jobs:
  build_and_push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest-16-cores
    outputs:
      "version": ${{ steps.build_push_sign.outputs.version }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@d5680102b2e7006e7b4184acc9604aa321176107 # ratchet:nais/platform-build-push-sign@main
        id: build_push_sign
        with:
          name: console
          dockerfile: Dockerfile
          google_service_account: gh-console
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
  rollout:
    permissions:
      id-token: write
    needs: ["build_and_push"]
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: nais/fasit-deploy@b2c0b6d049b53bef41b321eec406fe66938576fd # ratchet:nais/fasit-deploy@main
        with:
          json: '{"backend": {"image": {"tag": "${{ needs.build_and_push.outputs.version }}"}}}'
          feature_name: console
