name: Check pull request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
      - name: Get go version
        id: go_version
        run: |
          echo "GO_VERSION=$(grep golang .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v4 # ratchet:exclude
        with:
          go-version: ${{ steps.go_version.outputs.GO_VERSION }}
      - name: make check
        run: make check
      - name: make test
        run: make test
      - name: helm package
        run: helm package ./charts/teams-backend --destination .
      - name: docker build
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        with:
          name: teams-backend
          push: false
