name: Build pull request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
      - uses: actions/setup-go@v4 # ratchet:exclude
        with:
          go-version: "1.21.x"
      - name: make check
        run: make check
      - name: make test
        run: make test
      - name: helm package
        run: helm package ./charts/teams-backend --destination .
      - name: docker build
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        with:
          name: teams-backend
          push: false
