name: Test build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
      - uses: nais/platform-build-push-sign@main # ratchet:exclude
        with:
          name: teams-backend
          push: false
